SVM Classifier

In [22]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from matplotlib import style
from sklearn import svm, datasets
from sklearn.model_selection import cross_val_score
style.use("ggplot")

In [11]:
df1 = pd.read_csv("svm-t-packets.csv")
data_df = df1[:100]
features = ["Ether","Lan","Phy_other","IP","IP_other","ARP","Len"]
x = np.array(data_df[features].values)
y = (data_df["Status"].values.tolist())

In [12]:
df1.dtypes
list(df1.columns.values)

['Unnamed: 0',
 'Ether',
 'Lan',
 'Phy_other',
 'IP',
 'IP_other',
 'ARP',
 'Len',
 'Status']

In [13]:
clf = svm.SVC(kernel="linear", C= 1.0)
clf.fit(x,y)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [16]:
clf.predict([[1, 0,0,1,0,0,52]])

array([1])

In [17]:
clf.support_vectors_

array([[ 1.,  0.,  0.,  1.,  0.,  0., 52.],
       [ 1.,  0.,  0.,  1.,  0.,  0., 40.],
       [ 1.,  0.,  0.,  1.,  0.,  0., 52.],
       [ 1.,  0.,  0.,  1.,  0.,  0., 40.]])

In [18]:
clf.support_

array([ 0, 20, 78, 99], dtype=int32)

In [19]:
clf.n_support_

array([2, 2], dtype=int32)

In [21]:
clf.kernel

'linear'

Calculate - score

Common cases: predefined values

In [23]:
iris = datasets.load_iris()

In [24]:
X, y = iris.data, iris.target

In [25]:
clf = svm.SVC(probability=True, random_state=0)

In [26]:
cross_val_score(clf, X, y, scoring='neg_log_loss') 

array([-0.07475338, -0.16911634, -0.0698804 ])

In [27]:
model = svm.SVC()

In [28]:
cross_val_score(model, X, y, scoring='wrong_choice')

ValueError: 'wrong_choice' is not a valid scoring value. Valid options are ['accuracy', 'adjusted_mutual_info_score', 'adjusted_rand_score', 'average_precision', 'completeness_score', 'explained_variance', 'f1', 'f1_macro', 'f1_micro', 'f1_samples', 'f1_weighted', 'fowlkes_mallows_score', 'homogeneity_score', 'mutual_info_score', 'neg_log_loss', 'neg_mean_absolute_error', 'neg_mean_squared_error', 'neg_mean_squared_log_error', 'neg_median_absolute_error', 'normalized_mutual_info_score', 'precision', 'precision_macro', 'precision_micro', 'precision_samples', 'precision_weighted', 'r2', 'recall', 'recall_macro', 'recall_micro', 'recall_samples', 'recall_weighted', 'roc_auc', 'v_measure_score']

metric functions

In [30]:
from sklearn.metrics import fbeta_score, make_scorer

In [31]:
ftwo_scorer = make_scorer(fbeta_score, beta=2)

In [32]:
from sklearn.model_selection import GridSearchCV

In [33]:
from sklearn.svm import LinearSVC

In [34]:
grid = GridSearchCV(LinearSVC(), param_grid={'C': [1, 10]}, scoring=ftwo_scorer)

In [ ]:
import numpy as np
def my_custom_loss_func(ground_truth, predictions):
    diff = np.abs(ground_truth - predictions).max()
    return np.log(1 + diff)